// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MuzikSitesi.Data;

#nullable disable

namespace MuzikSitesi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520000000_AddRentalDueDate")]
    partial class AddRentalDueDate
    {
    }
}
