// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuzikSitesi.Data;

#nullable disable

namespace MuzikSitesi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421102933_ModellerGuncellendi")]
    partial class ModellerGuncellendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("MuzikSitesi.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.ToTable("Albumler");
                });

            modelBuilder.Entity("MuzikSitesi.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Katilimcilar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kurucusu")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("MuzikSitesi.Models.Album", b =>
                {
                    b.HasOne("MuzikSitesi.Models.Grup", "Grup")
                        .WithMany("Albumler")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("MuzikSitesi.Models.Grup", b =>
                {
                    b.Navigation("Albumler");
                });
#pragma warning restore 612, 618
        }
    }
}
